name: Deploy Gold-Silver Inventory

on:
  workflow_run:
    workflows:
      - Build and Publish Docker Images
    types:
      - completed
    branches:
      - FIM
      - main

  workflow_dispatch:

jobs:
  deploy:
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /docker/goldsilver_app
            docker compose pull
            docker compose up -d --remove-orphans
            docker compose ps
